version: '2'
services:
  frontend:
    build: "./frontend"
    volumes:
     - ./frontend:/usr/share/nginx/html
    environment:
     - API_URL=http://localhost:8080
    ports:
     - "9000:80"
    depends_on:
    - backend
  backend:
    build: "./backend"
    volumes:
     - ./backend:/usr/src/app
    ports:
     - "8080:8080"
    links:
      - mongo
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"